### ISSUE TITLE
Expired WSATest certificate

### ISSUE THREAD

**Issue by AdamArena** [microsoft/mixed-reality-robot-interaction-demo#10]
Hi team!

Encountered an issue when deploying Demo 1 to the Hololens2. 
I found I couldn't build through Unity because it resulted in an 'expired WSAT certificate' error. After some searching I discovered that if I simply deleted this certificate in the Assets folder I could continue with the build.

Now when attempting to deploy to the Hololens2 through Visual Studio I recieve an error 'Unable to activate Windows Store app 'MSIROSinteractiondemo..etc 'Access is denied'. It would seem now that trying to delete my way out of the issue has caught up with me! 

Any ideas? Happy to recreate the issue and take screenshots if that would help. 

Best,
Adam

**Comment by EricVoll** [comment]
Hi @AdamArena 
Thanks for raising this issue and sorry for coming back to you so late!
It seems #13 has the same issue and found a solution. We'll have a look at it.
Eric

**Comment by EricVoll** [comment]
I'll close this issue for now, since I expect the issue to be solved on the latest master. If it still persists, please fell free to reopen it again.
-Eric
