### ISSUE TITLE
How long is the software available?

### ISSUE THREAD

**Issue by danneboom** [microsoft/mixed-reality-robot-interaction-demo#7]
I'd love to run your nice tutorial, but at the moment there's no time at all for it. Do I have to worry about this repo and the docker containers being deleted at some point? Or can I safely follow your workshop next year as well? (Once I got a hololens for example).

Thanks in advance!

**Comment by EricVoll** [comment]
Hi @danneboom 

The repo will definitely stay up for quite some time. Currently there are no plans to take it down at all as there is really no reason to 🙂
I do not know about the containers and will find that out for you. Currently there are no plans to take them down either.

But in the "Build from source" section all the instructions to re-build the containers themselves are documented as well. The "docker" folder in this repo contains the Dockerfiles needed for that.

Best
Eric

**Comment by helenol** [comment]
@danneboom There are no plans to take anything down, and the IROS tutorial videos will be re-uploaded to youtube once IROS is over. :) (And we'll post the links as soon as that's done).

**Comment by danneboom** [comment]
Awesome news, thanks you!

**Comment by srsidd** [comment]
On a related note, is there a way to access the video? The link in the `readme` points to the IROS website which unfortunately has removed the videos since late January :-(

**Comment by EricVoll** [comment]
There were plans to upload these videos to youtube as well, but maybe @jeffdelmerico has some information on that?

**Comment by jeffdelmerico** [comment]
The "lecture" portion of the IROS tutorial is now available in a slightly condensed format as part of a Microsoft Research webinar.  It was broadcast around the time that the IROS content was taken down, but it can be viewed on-demand here:
[https://note.microsoft.com/MSR-Webinar-Reality-and-Robotics-Registration-On-Demand.html](https://note.microsoft.com/MSR-Webinar-Reality-and-Robotics-Registration-On-Demand.html)
This is now updated in the `readme`.

The videos for the walkthrough of the hands-on parts of the tutorial are not yet on YouTube, but I will update the readme and re-close this thread once they are available there.

**Comment by jeffdelmerico** [comment]
The demo videos from IROS have now been uploaded to YouTube:
[Demo 1: Interaction](https://youtu.be/4G3wjPIs4Fc)
[Demo 2: Colocalization](https://youtu.be/P11LcMOp2CE)

These links will also be added to the readme.
