### ISSUE TITLE
Cannot find ASA anchor

### ISSUE THREAD

**Issue by jstiefel** [microsoft/mixed-reality-robot-interaction-demo#8]
I'm not able to locate any ASA anchors. I followed the instructions, put the base coordinate system to some position on the ground and clicked "Create ASA anchor". The Logger tells me:

```
CreateSpatialAnchor
Attempting to create anchor
Create a cloud spatial anchor with ID = f8c...
```

I then exit the application and restart it. When I click on "Find ASA anchor" (and try to look at the same location in the room), I regularly get "CloudManager_ErrorServerError: Service unavailable or unspecified error found" in the Logger. Furthermore, on Azure I don't see any created anchors.

Is there a way to get some more debugging messages? I can see a "Development Console" in the corner of my eye, but I can hardly read anything there.

**Comment by EricVoll** [comment]
Hi @jstiefel 
I guess something in the way anchors are queried changed in the C# API. I am having the same issues. Maybe I have the time this weekend to play around with it and update the implementation. 
The anchors can be queried from other devices (just tested that) using the Linux SDK for example. So it has to be an issue with the querying. 
Cheers,
Eric

**Comment by jstiefel** [comment]
Thanks @EricVoll

It's not urgent for me. I was just wondering if I'm doing something wrong here. But in this case I'm now following all the other tutorials on Microsoft to get an overview how these queries are made.

Best,

Julian

**Comment by EricVoll** [comment]
Hi @jstiefel
Sorry, took some time! I just updated the ASA SDK version and tested everything. Now it seems to work perfectly for me. Are you still actively looking into the ASA functionalities?

**Comment by jstiefel** [comment]
Hi @EricVoll 

Thanks for the update. I'm currently not working on the Hololens project anymore.
